rhyme = input('enter the first line of a nursery ryhme')
amount = len(rhyme)
print('This has',amount,'letters in it')
number = int(input('enter a  starting number'))
number2 = int(input('enter a end number'))
print(rhyme[number:number2])
